---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example-1
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  postgresql:
    parameters:
      max_connections: '2000'
  storage:
    size: 10Gi
  resources:
    requests:
      memory: '500Mi'
      cpu: '600m'
    limits:
      memory: '500Mi'
      cpu: '600m'
